# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-04 14:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('seconds', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
                ('site_info', models.TextField(blank='true')),
            ],
        ),
    ]
